syntax = "proto3";

option go_package = ".";

package auth;

import "google/protobuf/empty.proto";

message TokenResponse {
  string access_token = 1;
}

message LoginRequest {
  string email = 1;
  string password = 2;  
}

message LoginResponse {
  bool status = 1;
  string message = 2;
  TokenResponse data = 3;
}

message LogoutResponse {
  bool status=1;
  string message =2;
}

service AuthService {
  rpc Login (LoginRequest) returns (LoginResponse) {};
  rpc Logout (google.protobuf.Empty) returns (LogoutResponse) {};
}